language: node_js
node_js:
  - 12
addons:
  apt:
    packages:
      - libgconf-2-4
branches:
  only:
    - master
cache:
  npm: true
  directories:
    - "~/.cache"
env:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  - ORG=digitaleng
before_install:
  - openssl aes-256-cbc -K $encrypted_79a2f6093848_key -iv $encrypted_79a2f6093848_iv
    -in assets/server.key.enc -out assets/server.key -d
  - export SFDX_AUTOUPDATE_DISABLE=false
  - export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
  - export SFDX_DOMAIN_RETRY=300
  - export SFDX_DISABLE_APP_HUB=true
  - export SFDX_LOG_LEVEL=DEBUG
  - mkdir sfdx
  - wget -qO- $URL | tar xJ -C sfdx --strip-components 1
  - "./sfdx/install"
  - export PATH=./sfdx/$(pwd):$PATH
  - sfdx --version
  - sfdx plugins --core
  - sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a $ORG
install:
  - yarn
script:
  - sfdx force:org:create -v $ORG -s -f config/project-scratch-def.json -a $TRAVIS_PULL_REQUEST_BRANCH --wait 3
  - sfdx force:org:display -u $TRAVIS_PULL_REQUEST_BRANCH
  - sfdx force:source:push -u $TRAVIS_PULL_REQUEST_BRANCH
  # - sfdx force:apex:test:run -u ciorg --wait 10
  - yarn cy:run --env orgAlias=$TRAVIS_PULL_REQUEST_BRANCH
  - sfdx force:org:delete -u $TRAVIS_PULL_REQUEST_BRANCH -p
