name: Cypress Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    env:
      # Use org to target tests via variable.
      ORG: ${{ secrets.SF_ORG }}
      SFDX_AUTOUPDATE_DISABLE: false
      SFDX_USE_GENERIC_UNIX_KEYCHAIN: true
      SFDX_DOMAIN_RETRY: 300
      SFDX_DISABLE_APP_HUB: true
      SFDX_LOG_LEVEL: DEBUG
      SF_DL_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup code
        run: |
          openssl aes-256-cbc -K $encrypted_79a2f6093848_key -iv $encrypted_79a2f6093848_iv -in assets/server.key.enc -out assets/server.key -d
          mkdir sfdx
          wget -qO- $URL | tar xJ -C sfdx --strip-components 1
          "./sfdx/install"
          export PATH=./sfdx/$(pwd):$PATH
          sfdx --version
          sfdx plugins --core
          sfdx force:config:list
          sfdx force:auth:jwt:grant -d -a $ORG --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME
          sfdx force:org:list --all --verbose

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/automated/**/*
          # build: yarn build
          # start: yarn start
